# Generated by Django 4.2 on 2024-04-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='related_courses',
        ),
        migrations.AddField(
            model_name='course',
            name='questions',
            field=models.JSONField(blank=True, default=dict, verbose_name='self'),
        ),
    ]
